version: '3.8'

services:
  db:
    image: mysql:8
    container_name: linknest-db
    restart: always
    environment:
      MYSQL_DATABASE: linknest
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: linknest
      MYSQL_PASSWORD: linknest123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: linknest-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/linknest
      DB_USER: linknest
      DB_PASS: linknest123
    depends_on:
      - db

volumes:
  db_data:
